// CONSTANTS
const DIFFICULTY = 2;
const NONCE = 0;
const MINE_RATE = 3000;
const MINING_REWARD = 50;

// Wallet
const INITIAL_BALANCE = 500;

module.exports = { DIFFICULTY, NONCE, MINE_RATE, INITIAL_BALANCE, MINING_REWARD };
